### ISSUE TITLE
Could use a command which verifies that all strings have been localized

### ISSUE THREAD

**Issue by qtehfw** [jayrave/android_localization#3]
When using `android_localization` in a CD/CI workflow, it would be useful for there to be a command that exits successfully when all strings have been localized, to use as a verification step before the `localize` command is called. This is because the latter operates under the assumption that there ARE strings that require localization, and exits with an error if all strings have already been localized.

**Comment by jayrave** [comment]
https://github.com/jayrave/android_localization/releases/tag/0.1.8 addresses this

**Comment by jayrave** [comment]
Thanks for the request!
